# Generated by Django 3.0.6 on 2020-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.FileField(upload_to='images/'),
        ),
    ]
